name: TicketManager
main: net.dawn.mc.micheldewit.plugin.Modreq
version: 1.2.0
author: Micheldewit
softdepends: []
description: Serverside Ticketmanager, goes in coop with TicketMan-Web services.

commands:
   ticket:
     description: Token management command.
     aliases: [tokens]

permissions:
  TickerManager.Staff:
    description: Grants access to all TicketManager Permissions.

