name: ${project.artifactId}
version: ${project.version}
description: A facade similar to Vault that abstracts the coder from the JDBC and each database driver's implementation.
author: PatPeter
main: lib.PatPeter.SQLibrary.SQLibrary